### ISSUE TITLE
Error: Can't subset columns that don't exist

### ISSUE THREAD

**Issue by farahaawad** [markusfritsch/pdynmc#1]
I keep getting this error when I use the pdynmc function, even though I can see that the column exists in my dataset. 
Error: Can't subset columns that don't exist. x Locations 14, 15, 16, 2, 17, etc. don't exist. i There are only 1 column

**Comment by markusfritsch** [comment]
Can you provide me with the code and data you are using? So that I have a starting point for digging into the issue. If you are not comfortable sharing the code, feel free to send me the material via email.

**Comment by farahaawad** [comment]
Dear Mark,
Thank you for your prompt response. Unforfutently, the data I’m using is confidential for the institution I’m working with. However, I tried the code with a small dataset which I made up (attached) and got the same error.

The code I have used:
GMM2 <- pdynmc(dat= test_data, varname.i = "ID", varname.t = "Year",use.mc.diff = FALSE, use.mc.lev = FALSE, use.mc.nonlin = FALSE, include.y = TRUE, varname.y = "Y", lagTerms.y = 1, fur.con = TRUE, fur.con.diff = FALSE,fur.con.lev = TRUE, varname.reg.fur = c("X1", "X2"),lagTerms.reg.fur = c(0), include.dum = FALSE,  dum.diff = FALSE, dum.lev = FALSE, w.mat="iid.err", std.err = "corrected", estimation = "onestep")

The error:
Error: Can't subset columns that don't exist. x Locations 2, 3, and 4 don't exist. i There are only 1 column.

Please advise.

Best regards,
Farah

**Comment by farahaawad** [comment]
Hi, 
gentle reminder

**Comment by markusfritsch** [comment]
Dear Farah,

there are two things going on here.

(1) You are estimating a linear dynamic panel data model based on linear and/or nonlinear moment conditions with pdynmc(). In your code, you are not using any moment conditions (as arguments use.mc.diff, use.mc.lev, and use.mc.nonlin are set to FALSE).
For more details on the method, see the [package vignette](https://cran.r-project.org/web/packages/pdynmc/vignettes/pdynmcVignette.pdf) and the documents linked there.

(2) You are using further controls in your model. Please note that the vector giving the names of the further controls (varname.reg.fur) and the vector specifying the dynamic structure of the further controls (lagTerms.reg.fur) need to have the same length.

Below is a code with a minimal working example:

install.packages("pdynmc")
library(pdynmc)
install.packages("plm")
library(plm)

data(EmplUK)
test_data 		<- EmplUK[1:105, c(1:2, 4:6)]
names(test_data)	<- c("ID", "Year", "Y", "X1", "X2")

GMM2 <- pdynmc(dat= test_data, varname.i = "ID", varname.t = "Year",
	use.mc.diff = TRUE, use.mc.lev = FALSE, use.mc.nonlin = FALSE,
	include.y = TRUE, varname.y = "Y", lagTerms.y = 1, fur.con = TRUE,
	fur.con.diff = FALSE,fur.con.lev = TRUE, varname.reg.fur = c("X1", "X2"),lagTerms.reg.fur = c(0,0),
	include.dum = FALSE,  dum.diff = FALSE, dum.lev = FALSE,
	 w.mat="iid.err", std.err = "corrected", estimation = "onestep")

Best regards
Markus
