### ISSUE TITLE
htest objects (jtest.fct, mtest.fct) and default for mtest.fct(. , t.order)

### ISSUE THREAD

**Issue by tappek** [markusfritsch/pdynmc#3]
I noticed the htest objects produced by `jtest.fct`, `mtest.fct` are somewhat non-standard (if there is any standard):

- I suggeest to add a `alternative` list entry and put the alt. hypothesis in there, so it will be printed automatically by `print.htest`

- Putting info about the estmated model and H0 under `htest_object$data` looks a bit akward in printing. If the alternative is given, there is no need to print H0.

For `mtest.fct`'s `t.order` argument, I suggest to put a default so it "simply runs" when executed without user specified `t.order`.

**Comment by tappek** [comment]
Similar comments apply to `wald.fct`. Additionally, the order of argument for `wald.fct` is somewhat surprising (but maybe too late to change?).

**Comment by markusfritsch** [comment]
@tappek: Thank you for your comments and suggestions! I adjusted the functions accordingly.

**Comment by tappek** [comment]
glad that you found my suggestions useful. Btw: if you ever want to get rid of the `.fct` extension for these functions, we can align to introduce a generic as there is `mtest` in package `plm` and then have `mtest.pgmm` and `mtest.pdynmc` methods.

**Comment by markusfritsch** [comment]
this also sounds like a very good idea. I will look into it during the next couple of days and get back to you.

**Comment by tappek** [comment]
`mtest` in `plm`'s development version from rev. 1297 is generic https://r-forge.r-project.org/scm/?group_id=4067 and from plm 2.4-2 onwards as on CRAN since 2021-09-21.
